spring.application.name=roomRental


#Database Config
spring.datasource.url=jdbc:postgresql://localhost:4445/room_rental_db
spring.datasource.username=dara
spring.datasource.password=Admin@2025
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect